#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : F-Engrave
Version  : 1.71
Release  : 8
URL      : http://www.scorchworks.com/Fengrave/F-Engrave-1.71_src.zip
Source0  : http://www.scorchworks.com/Fengrave/F-Engrave-1.71_src.zip
Summary  : Supports Engraving and V-Carving
Group    : Development/Tools
License  : GPL-3.0
Requires: F-Engrave-bin = %{version}-%{release}
Requires: potrace
BuildRequires : dos2unix
BuildRequires : freetype-dev
BuildRequires : potrace
Patch1: build.patch

%description
No detailed description available

%package bin
Summary: bin components for the F-Engrave package.
Group: Binaries

%description bin
bin components for the F-Engrave package.


%prep
%setup -q -n F-Engrave-1.71_src
cd %{_builddir}/F-Engrave-1.71_src
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1582818484
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1582818484
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/f-engrave
/usr/bin/ttf2cxf_stream
